{
 "title": "01.RECKITT PROJECT(SOFT SUPPLY SYSTEM)",
 "tags": [
  "RECKITT",
  "LPE_PROJECT"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 0, "y": 0 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 36px;'>Liquid Purification Engineering International Co., Ltd.</span></h4>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 0 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>SOFT SUPPLY SYSTEM</span></h4>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 2 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>UF SYSTEM</span></h4>"
   }
  },
  { "title": "PROJECT", "type": "dashlist", "gridPos": { "h": 4, "w": 7, "x": 17, "y": 2 } },
  {
   "title": "UF FEED PRESSURE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "psi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF FEED PRESSURE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device2",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF PRODUCT PRESSURE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "psi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF PRODUCT PRESSURE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device3",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF TMP.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "psi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF TMP.",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device4",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF FEED FLOW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF FEED FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device5",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF PRODUCT FLOW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF PRODUCT FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device6",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "POTABLE TANK CHLORINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "POTABLE TANK CHLORINE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device1",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF PRODUCT CHLORINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF PRODUCT CHLORINE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device7",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "POTABLE TANK TK-1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "POTABLE TANK TK-1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device8",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF PRODUCT TK-2A/2B",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF PRODUCT TK-2A/2B",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device9",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF PRODUCT TOTAL FLOW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF PRODUCT TOTAL FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device11",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF FEED TOTAL FLOW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF FEED TOTAL FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device10",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF HOUR RUN METER",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF HOUR RUN METER",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device12",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "title": "PRESSURE  UF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    {
     "alias": "UF FEED PRESSURE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF PRODUCT PRESSURE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF TMP.",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FLOWRATE  UF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "alias": "UF FEED FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF PRODUCT FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CHLORINE UF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "POTABLE TANK CHLORINE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF PRODUCT CHLORINE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device7",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "LEVEL  UF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "PATABLE TANK TK-1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device8",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF PRODUCT TK-2A/2B",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device9",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TOTAL FLOW UF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "alias": "UF FEED TOTAL FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "UF PRODUCT TOTAL FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device11",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HOURS RUN UF SYSTEM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Hour" } },
   "targets": [
    {
     "alias": "UF HOUR RUN METER",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device12",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "POTABLE TANK CHLORINE(AE101)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF FEED PRESSURE (PT101)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF PRODUCT PRESSURE(PT102)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF TMP.(PT101-PT12)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF FEED FLOW(FIT101)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF PRODUCT FLOW(FIT102)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF PRODUCT CHLORINE(AE201)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device7",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "PATABLE TANK TK-1(LT101)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device8",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF PRODUCT TK-2A/2B (LT201)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device9",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF FEED TOTAL FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF PRODUCT TOTAL FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device11",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF HOUR RUN METER",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device12",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 55 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 58 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>NF SYSTEM</span></h4>"
   }
  },
  {
   "title": "NF FEED ORP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NF FEED ORP",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device13",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NF FEED PRESSURE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "psi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NF FEED PRESSURE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device14",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NF FEED ARRAY#2 PRESSURE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "psi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NF FEED ARRAY#2 PRESSURE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device15",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NF REJECT PRESSURE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "psi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NF REJECT PRESSURE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device16",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NF DIFF PRESSURE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "psi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NF DIFF PRESSURE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device17",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NF FEED CONDUCT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "uS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NF FEED CONDUCT",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device18",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NF PERMEATE CONDUCT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "uS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NF PERMEATE CONDUCT",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device19",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NF FEED FLOW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NF FEED FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device20",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NF PRODUCT FLOW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NF PRODUCT FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device21",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NF REJECT FLOW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NF REJECT FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device22",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NF FEED TOTAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NF FEED TOTAL",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device23",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NF PRODUCT TOTAL FLOW  ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NF PRODUCT TOTAL FLOW  ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device24",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NF REJECT TOTAL FLOW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NF REJECT TOTAL FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device25",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NF HOUR RUN METER",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "NF HOUR RUN METER",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device26",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "title": "PRESSURE NF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    {
     "alias": "NF FEED PRESSURE(PT203)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device14",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device31\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF FEED ARRAY#2 PRESSURE(PT204)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device15",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device31\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF REJECT PRESSURE(PT205)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device16",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device31\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF DIFF PRESSURE (PT204-PT205)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device17",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device31\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FLOWRATE NF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "alias": "NF FEED FLOW(FIT201) ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device20",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF PRODUCT FLOW(FIT202) ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device21",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF REJECT FLOW (FIT201-FIT202)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device22",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ORP NF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "alias": "NF FEED ORP (AE202)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device13",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CONDUCTIVITY NF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "uS/cm" } },
   "targets": [
    {
     "alias": "NF FEED CONDUCT(CE201)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device18",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF PERMEATE CONDUCT(CE202)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device19",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TOTAL VOLUME NF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "alias": "NF FEED TOTAL VOLUME",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device23",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF PRODUCT TOTAL VOLUME",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device24",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF REJECT TOTAL VOLUME",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device25",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": " HOURS RUN NF SYSTEM",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "Hour" } },
   "targets": [
    {
     "alias": "NF HOUR RUN METER",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device26",
     "query": "SELECT last(\"value\") FROM \"Site1/machine1/device42\" WHERE $timeFilter GROUP BY time(1m) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "NF FEED ORP(AE202)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device13",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF FEED PRESSURE(PT203)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device14",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF FEED ARRAY#2 PRESSURE(PT204)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device15",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF REJECT PRESSURE(PT205)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device16",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF DIFF PRESSURE(PT204-PT205)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device17",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF FEED CONDUCT(CE201)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device18",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF PERMEATE CONDUCT(CE202)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device19",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF FEED FLOW(FIT201) ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device20",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF PRODUCT FLOW(FIT202)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device21",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF REJECT FLOW(FIT201-FIT202)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device22",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF FEED TOTAL",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device23",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF PRODUCT TOTAL FLOW ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device24",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF REJECT TOTAL FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device25",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "NF HOUR RUN METER",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device26",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 115 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 118 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'>SOFT SUPPLY SYSTEM</span></h4>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'></span></h4>"
   }
  },
  {
   "title": "SOFT SUPPLY PRESSURE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "psi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SOFT SUPPLY PRESSURE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device27",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOFT SUPPLY FLOW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SOFT SUPPLY FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device30",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOFT RETURN FLOW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SOFT RETURN FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device31",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOFT SUPPLY CONDUCT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "uS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SOFT SUPPLY CONDUCT",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device29",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOFT SUPPLY CHLORINE ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SOFT SUPPLY CHLORINE ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device28",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOFT WATER TANK TK-3",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SOFT WATER TANK TK-3",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device32",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOFT SUPPLY TOTAL FLOW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SOFT SUPPLY TOTAL FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device33",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOFT RETURN TOTAL FLOW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SOFT RETURN TOTAL FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device34",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOFT WATER USAGE TOTAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SOFT WATER USAGE TOTAL",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device35",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site1/machine1/device1\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "title": "PRESSURE  SOFT SUPPLY SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    {
     "alias": "SOFT SUPPLY PRESSURE(LT201)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device27",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "SOFT SUPPLY PRESSURE(LT201)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device27",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FLOWRATE  SOFT SUPPLY SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "alias": "SOFT SUPPLY FLOW (FE301)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device30",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "SOFT RETURN FLOW (FE302)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device31",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CHLORINE SOFT SUPPLY SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "SOFT SUPPLY CHLORINE(AE301) ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device28",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CONDUCTIVITY SOFT SUPPLY SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "uS/cm" } },
   "targets": [
    {
     "alias": "SOFT SUPPLY CONDUCT.(CE301) ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device29",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOFT WATER TANK LEVEL",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "SOFT WATER TANK TK-3(LT301) ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device32",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TOTAL VALUME  SOFT SUPPLY SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "alias": "SOFT SUPPLY TOTAL FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device33",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "SOFT RETURN TOTAL FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device34",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "SOFT WATER USAGE TOTAL",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device35",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOFT SUPPLY SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "SOFT SUPPLY PRESSURE(LT201)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device27",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "SOFT SUPPLY CHLORINE(AE301)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device28",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "SOFT SUPPLY CONDUCT.(CE301)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device29",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "SOFT SUPPLY FLOW(FE301)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device30",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "SOFT RETURN FLOW(FE302)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device31",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "SOFT WATER TANK TK-3(LT301)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device32",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "SOFT SUPPLY TOTAL FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device33",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "SOFT RETURN TOTAL FLOW",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device34",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "SOFT WATER USAGE TOTAL",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site1/machine2/device35",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 170 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 172 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>ALARM</span></h4>"
   }
  },
  {
   "title": "Alarm",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 174 },
   "targets": [
    {
     "alias": "Alarm Comment",
     "measurement": "Site1/machine2/Alarm1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}