{
 "title": "02.MICROSHIP PROJECT",
 "tags": [ "LPE_PROJECT" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 36px;'>Liquid Purification Engineering International Co., Ltd.</span></h4>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>Microchip</span></h4>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>RO SYSTEM 1</span></h4>"
   }
  },
  {
   "title": "1st RO Feed Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Feed ORP",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO Concentrate Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "1st RO Concentrate Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO Feed Conductivity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "uS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "1st RO Feed Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device2",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site2/machine1/device2\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO Permeate Conductivity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "uS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "1st RO Permeate Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device3",
     "query": "SELECT last(\"value\") FROM \"Site2/machine1/device3\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO %Salt Rejection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "1st RO %Salt Rejection",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO Flush Counter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "1st.RO Recycle Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO Run Time Per Day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "1st RO Run Time Per Day",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device7",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO Operation Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "1st RO Operation Time",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 7 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "title": "RRESSURE  RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "alias": "1st RO Feed Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "1st RO Concentrate Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CONDUCTIVITY RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "us/cm" } },
   "targets": [
    {
     "alias": "1st RO Feed Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "1st RO Permeate Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO %Salt Rejection",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "alias": "2nd RO Feed pH",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO Operation Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "hour" } },
   "targets": [
    {
     "alias": "1st RO Operation Time",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO Flush Counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "1st RO Flush Counter",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO Run Time Per Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "alias": "1st RO Run Time Per Day",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device7",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>RO SYSTEM 2</span></h4>"
   }
  },
  {
   "title": "2nd RO Feed Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "2nd RO Feed Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device8",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "2nd RO Concentrate Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "2nd RO Concentrate Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device9",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "2nd RO Feed Conductivity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "uS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "2nd RO Feed Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "2nd RO Permeate Conductivity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "uS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "2nd RO Permeate Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device11",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "2nd RO %Salt Rejection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "2nd RO %Salt Rejection",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device12",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "2nd RO Feed pH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "2nd RO Feed pH",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device13",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO Run Time Per Day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "2nd RO Run Time Per Day",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device15",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "2nd RO Operation Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "2nd RO Operation Time",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device14",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 37 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "title": "RRESSURE  RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "alias": "1st RO Feed Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device8",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "1st RO Concentrate Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device9",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CONDUCTIVITY RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "us/cm" } },
   "targets": [
    {
     "alias": "1st RO Feed Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "1st RO Permeate Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device11",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO %Salt Rejection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "2nd RO Feed pH",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device12",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "2nd RO Feed pH",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "2nd RO Feed pH",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device13",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO Operation Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "hour" } },
   "targets": [
    {
     "alias": "1st RO Operation Time",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device14",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1st RO Run Time Per Day",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "alias": "1st RO Run Time Per Day",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device15",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO SYSTEM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "1stRO Feed P",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "1stRO Conc P",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "1stRO Feed C",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "1stRO Prod C",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "1stRO Hr",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "1stRO Flush Count",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "1stRO Run Hr/day",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site2/machine1/device7",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "2ndRO Feed P",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device8",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "2ndRO Conc P",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device9",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "2ndRO Feed C",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "2ndRO Prod C",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device11",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "2ndRO pH",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device13",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "2ndRO Hr",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device14",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "2ndRO Hr/day",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site2/machine2/device15",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 74 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 76 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>ALARM</span></h4>"
   }
  },
  {
   "title": "Alarm",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "alias": "Alarm Comment",
     "measurement": "Site2/machine1/Alarm1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}