{
 "title": "04.HAAD THIP PROJECT",
 "tags": [ "LPE_PROJECT" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 36px;'>Liquid Purification Engineering International Co., Ltd.</span></h4>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>HAAD THIP</span></h4>"
   }
  },
  {
   "title": "Ultrafiltration System (UF#4-UF#5)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>Ultrafiltration System (UF#4-UF#5)</span></h4>"
   }
  },
  {
   "title": "UF#4 feed pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF#4 feed pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF#4 product pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF#4 product pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF#4 TMP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF#4 TMP",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF#4 product flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF#4 product flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device7",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF#4 product volume ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF#4 product volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device8",
     "query": "SELECT last(\"value\")  / 1 FROM \"Site4/machine1/device8\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF#4 operation time ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF#4 operation time ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device9",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF#5 feed pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF#5 feed pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device15",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF#5 product pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF#5 product pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device16",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF#5 TMP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF#5 TMP",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device17",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF#5 product flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF#5 product flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device18",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site4/machine1/device18\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF#5 product volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF#5 product volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device19",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site4/machine1/device18\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF#5 operation time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UF#5 operation time",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device20",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "title": "PRESSURE UF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "targets": [
    {
     "alias": "UF#4 feed pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF#4 product pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF#4 TMP",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF#5 feed pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device15",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF#5 product pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device16",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF#5 TMP",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device17",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FLOWRATE  UF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "alias": "UF#4 product flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device7",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF#5 product flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device18",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PRODUCT VOLUME UF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "alias": "UF#4 product volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device8",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF#5 product volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device19",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "OPERATION TIME UF SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Hour" } },
   "targets": [
    {
     "alias": "UF#4 operation time",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device9",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UF#5 operation time",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device20",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ALL Ultrafiltration  SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "1 UF#4 feed pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "2 UF#4 product pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "3 UF#4 TMP",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "4 UF#4 product flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device7",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "5 UF#4 product volume ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device8",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "6 UF#4 operation time ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device9",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "7 UF#5 feed pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device15",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "8 UF#5 product pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device16",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "9 UF#5 TMP",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device17",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "10 UF#5 product flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device18",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "11 UF#5 product volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device19",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "12 UF#5 operation time",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device20",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Reverse Osmosis System (RO#4)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>Reverse Osmosis System (RO#4)</span></h4>"
   }
  },
  {
   "title": "RO #4 Pre Filter Inlet Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #4 Pre Filter Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device31",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #4 Pre Filter Outlet Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #4 Pre Filter Outlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device32",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "∆P RO #4 Pre Filter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "∆P RO #4 Pre Filter",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device33",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #4 Array 1 Inlet Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #4 Array 1 Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device34",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #4 Array 2 Inlet Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #4 Array 2 Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device35",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #4 Concentrate Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #4 Concentrate Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device36",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "∆P RO #4 Array 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "∆P RO #4 Array 1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device37",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "∆P RO #4 Array 2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "∆P RO #4 Array 2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device38",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "∆P RO #4 System",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "∆P RO #4 System",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device39",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "MC-4 Outlet Vacuum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "MC-4 Outlet Vacuum",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device55",
     "query": "SELECT last(\"value\")  / 100 FROM \"Site4/machine1/device55\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #4 Feed Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "m3/hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #4 Feed Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device40",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #4 Product Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "m3/hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #4 Product Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device41",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO#4 reject flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "m3/hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO#4 reject flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device42",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #4 % Recovery",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #4 % Recovery",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device43",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #4 Feed Conductivity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "μS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #4 Feed Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device46",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #4 Product Conductivity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "μS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #4 Product Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device47",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #4 % Salt Rejection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #4 % Salt Rejection",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device48",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #4 Total Product Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #4 Total Product Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device44",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #4 Total Reject Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #4 Total Reject Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device45",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #4 Run Hour Meter ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #4 Run Hour Meter ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device50",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "title": "PRESSURE  RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "targets": [
    {
     "alias": "RO #4 Pre Filter Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device31",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #4 Pre Filter Outlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device32",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "∆P RO #4 Pre Filter",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device33",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #4 Array 1 Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device34",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #4 Array 2 Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device35",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #4 Concentrate Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device36",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "∆P RO #4 Array 1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device37",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "∆P RO #4 Array ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device38",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "∆P RO #4 System",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device39",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "MC-4 Outlet Vacuum",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device55",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FLOWRATE  RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "alias": "RO #4 Feed Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device40",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #4 Product Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device41",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO#4 reject flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device42",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Conductivity RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "μS/cm" } },
   "targets": [
    {
     "alias": "RO #4 Feed Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device46",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #4 Product Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device47",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Salt Rejection and Recovery RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "RO #4 % Salt Rejection",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device48",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #4 % Recovery",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device42",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "VOLUME  RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "alias": "RO #4 Total Product Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device44",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #4 Total Reject Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device45",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Run Hour Meter  RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "Hour" } },
   "targets": [
    {
     "alias": "RO #4 Run Hour Meter ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device50",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ALL Reverse Osmosis System (RO#4)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "1 RO #4 Pre Filter Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device31",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "2 RO #4 Pre Filter Outlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device32",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "3 ∆P RO #4 Pre Filter",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device33",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "4 RO #4 Array 1 Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device34",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "5 RO #4 Array 2 Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device35",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "6 RO #4 Concentrate Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device36",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "7 ∆P RO #4 Array 1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device37",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "8 ∆P RO #4 Array 2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device38",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "9 ∆P RO #4 System",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device39",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "10 RO #4 Feed Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device40",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "11 RO #4 Product Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device41",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "12 RO#4 reject flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device42",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "13 RO #4 % Recovery",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device43",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "14 RO #4 Total Product Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device44",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "15 RO #4 Total Reject Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device45",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "16 RO #4 Feed Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device46",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "17 RO #4 Product Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device47",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "18 RO #4 % Salt Rejection",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device48",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "19 RO #4 Run Hour Meter ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device50",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "20 MC-4 Outlet Vacuum",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device55",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Reverse Osmosis System (RO#5)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 115 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>Reverse Osmosis System (RO#5)</span></h4>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "title": "RO #5 Pre Filter Inlet Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #5 Pre Filter Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device58",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #5 Pre Filter Outlet Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #5 Pre Filter Outlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device59",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "∆P RO #5 Pre Filter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "∆P RO #5 Pre Filter",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device60",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #5 Array 1 Inlet Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #5 Array 1 Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device61",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #5 Feed Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "m3/hr." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #5 Feed Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device67",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #5 Concentrate Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #5 Concentrate Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device63",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "∆P RO #5 Array 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "∆P RO #5 Array 1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device64",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "∆P RO #5 Array 2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "∆P RO #5 Array 2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device65",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "∆P RO #5 System",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "∆P RO #5 System",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device66",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "MC-5 Outlet Vacuum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "MC-5 Outlet Vacuum",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device82",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #5 Array 2 Inlet Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #5 Array 2 Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device62",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #5 Product Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "m3/hr." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #5 Product Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device68",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO#5 reject flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "m3/hr." } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO#5 reject flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device69",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #5 % Recovery",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #5 % Recovery",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device70",
     "query": "SELECT last(\"value\")  / 10 FROM \"Site4/machine1/device70\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #5 Feed Conductivity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "μS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #5 Feed Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device73",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #5 Product Conductivity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "μS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #5 Product Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device74",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #5 % Salt Rejection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #5 % Salt Rejection",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device75",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #5 Total Product Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #5 Total Product Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device71",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #5 Total Reject Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #5 Total Reject Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device72",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO #5 Run Hour Meter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "Hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO #5 Run Hour Meter ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device77",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "title": "PRESSURE  RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "targets": [
    {
     "alias": "RO #5 Pre Filter Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device58",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #5 Pre Filter Outlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device59",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "∆P RO #5 Pre Filter",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device60",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #5 Array 1 Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device61",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #5 Array 2 Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device62",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #5 Concentrate Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device63",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "∆P RO #5 Array 1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device64",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "∆P RO #5 Array 2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device65",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "∆P RO #5 System",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device66",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "MC-5 Outlet Vacuum",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device82",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FLOWRATE  RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "alias": "RO #5 Feed Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device67",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #5 Product Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device68",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO#5 reject flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device69",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": " Conductivity  RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "μS/cm" } },
   "targets": [
    {
     "alias": "RO #5 Feed Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device73",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #5 Product Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device74",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Salt Rejection and Recovery RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "RO #5 % Salt Rejection",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device75",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #5 % Recovery",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device70",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Volume  RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "alias": "RO #5 Total Product Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device71",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO #5 Total Reject Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device72",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Run Hour Meter RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "Hour" } },
   "targets": [
    {
     "alias": "RO #5 Run Hour Meter ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device77",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ALL Reverse Osmosis System (RO#5)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "1 RO #5 Pre Filter Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device58",
     "query": "SELECT last(\"value\")  / 100 FROM \"Site4/machine1/device4\" WHERE $timeFilter GROUP BY time(1m) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "2 RO #5 Pre Filter Outlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device59",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "3 ∆P RO #5 Pre Filter",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device60",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "4 RO #5 Array 1 Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device61",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "5 RO #5 Array 2 Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device62",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "6 RO #5 Concentrate Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device63",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "7 ∆P RO #5 Array 1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device64",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "8 ∆P RO #5 Array 2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device65",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "9 ∆P RO #5 System",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device66",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "10 RO #5 Feed Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device67",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "11 RO #5 Product Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device68",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "12 RO#5 reject flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device69",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "13 RO #5 % Recovery",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device70",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "14 RO #5 Total Product Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device71",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "15 RO #5 Total Reject Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device72",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "16 RO #5 Feed Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device73",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "17 RO #5 Product Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device74",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "18 RO #5 % Salt Rejection",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device75",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "19 RO #5 Run Hour Meter ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device77",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "20 MC-5 Outlet Vacuum",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device82",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "RO Brine (ROB-2)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 178 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 179 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>RO Brine (ROB-2)</span></h4>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 181 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "title": "RO Brine #2 Pre Filter Inlet Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Brine #2 Pre Filter Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device85",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO Brine #2 Pre Filter Outlet Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Brine #2 Pre Filter Outlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device86",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "∆P RO Brine #2 Pre Filter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "∆P RO Brine #2 Pre Filter",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device87",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO Brine #2 Feed Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Brine #2 Feed Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device88",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO Brine #2 Concentrate Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Brine #2 Concentrate Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device89",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "∆P RO Brine #2 System",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "∆P RO Brine #2 System",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device90",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO Brine #2 Feed Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "m3/hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Brine #2 Feed Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device91",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO Brine #2 Product Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "m3/hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Brine #2 Product Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device92",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ROB#2 reject flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "m3/hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "ROB#2 reject flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device93",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO Brine #2 % Recovery",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Brine #2 % Recovery",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device94",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO Brine #2 Feed Conductivity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "μS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Brine #2 Feed Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device97",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO Brine #2 Product Conductivity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "μS/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Brine #2 Product Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device98",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO Brine #2 % Salt Rejection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Brine #2 % Salt Rejection",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO Brine #2 Total Product Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Brine #2 Total Product Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device95",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO Brine #2 Total Reject Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Brine #2 Total Reject Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device96",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO Brine #2 Hour Meter ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "Hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Brine #2 Hour Meter ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device101",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 191 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'></span></h4>"
   }
  },
  {
   "title": "PRESSURE  RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "targets": [
    {
     "alias": "RO Brine #2 Pre Filter Inlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device85",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO Brine #2 Pre Filter Outlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device86",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "∆P RO Brine #2 Pre Filter",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device87",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO Brine #2 Feed Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device88",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO Brine #2 Concentrate Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device89",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "∆P RO Brine #2 System",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device90",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FLOWRATE  RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "alias": "RO Brine #2 Feed Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device91",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO Brine #2 Product Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device92",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "ROB#2 reject flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device93",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Conductivity RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "μS/cm" } },
   "targets": [
    {
     "alias": "RO Brine #2 Feed Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device97",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO Brine #2 Product Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device98",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Salt Rejection and Recovery RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "RO Brine #2 % Salt Rejection",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO Brine #2 % Recovery",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device94",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": " Volume RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "alias": "RO Brine #2 Total Product Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device95",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "RO Brine #2 Total Reject Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device96",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hour Meter  RO SYSTEM.",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "Hour" } },
   "targets": [
    {
     "alias": "RO Brine #2 Hour Meter ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device101",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ALL RO Brine (ROB-2)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "1 RO Brine #2 Pre Filter Inlet Pressu",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device85",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "2 RO Brine #2 Pre Filter Outlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device86",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "3 ∆P RO Brine #2 Pre Filter",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device87",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "4 RO Brine #2 Feed Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device88",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "5 RO Brine #2 Concentrate Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device89",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "6 ∆P RO Brine #2 System",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device90",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "7 RO Brine #2 Feed Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device91",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "8 RO Brine #2 Product Flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device92",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "9 ROB#2 reject flow",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device93",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "10 RO Brine #2 % Recovery",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device94",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "11 RO Brine #2 Total Product Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device95",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "12 RO Brine #2 Total Reject Volume",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device96",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "13 RO Brine #2 Feed Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device97",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "14 RO Brine #2 Product Conductivity",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device98",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "15 RO Brine #2 % Salt Rejection",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "16 RO Brine #2 Hour Meter ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device101",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "17 RO Post filter Outlet Pressure",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device105",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "RO Water Supply ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 241 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 242 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>RO Water Supply</span></h4>"
   }
  },
  {
   "title": "RO SUPPLY PRESSURE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO WATER SUPPLY PRESSURE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device105",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO WATER SUPPLY PRESSURE",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 247 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "alias": "RO WATER SUPPLY PRESSURE",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device105",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "ALARM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 258 } },
  {
   "title": "Alarm",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 259 },
   "targets": [
    {
     "alias": "Alarm Comment",
     "measurement": "Site4/machine1/Alarm1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}