{
 "title": "07.TCP(Rayong) Project",
 "tags": [
  "TCP(Rayong)",
  "LPE_PROJECT"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 14, "x": 0, "y": 0 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>Liquid Purification Engineering International Co., Ltd.</span></h4>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'>TCP(Rayong)</span></h4>"
   }
  },
  {
   "title": "Chlorinated Water Tank Level",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Chlorinated Water Tank Level",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device48",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO Feed Tank Level",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Feed Tank Level",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device49",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RO Water Tank Level",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RO Water Tank Level",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Site4/machine1/device50",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UF System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
     "options": {
      "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'>UF SYSTEM</span></h4>"
     }
    },
    {
     "title": "UF Pre-Filter Inlet Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 2, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UF Pre-Filter Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device01",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "UF Pre-Filter Diff Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UF Pre-Filter Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device02",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "UF Feed Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UF Feed Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device03",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "UF Product Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UF Product Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device04",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "UF System TMP",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UF System TMP",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device05",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "UF Feed Chlorine",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 2, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UF Feed Chlorine",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device14",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "UF Feed Flow",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "m3/hr" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UF Feed Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device06",
       "query": "SELECT last(\"value\")  / 10 FROM \"Site2/machine1/device2\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "UF Product Flow",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "m3/hr" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UF Product Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device07",
       "query": "SELECT last(\"value\")  / 10 FROM \"Site2/machine1/device2\" WHERE $timeFilter GROUP BY time(1m) fill(previous)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "UF Feed Total Volume",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UF Feed Total Volume",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device09",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "UF Product Total Volume",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UF Product Total Volume",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device10",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "UF Operation Time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Hr." } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UF Operation Time",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device08",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "UF Backwash Counter",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UF Backwash Counter",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device11",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "UF CEB#1 Counter",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UF CEB#1 Counter",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device12",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "UF CEB#2 Counter",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UF CEB#2 Counter",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device13",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "OVERALL SYSTEM",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 20, "x": 2, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "UF Pre-Filter Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device01",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Pre-Filter Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device02",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Feed Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device03",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Product Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device04",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF System TMP",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device05",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Feed Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device06",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Product Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device07",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Operation Time",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device08",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Feed Total Volume",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device09",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Product Total Volume",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device10",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Backwash Counter",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device11",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF CEB#1 Counter",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device12",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF CEB#2 Counter",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device13",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Feed Chlorine",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device14",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RO System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "RO Operation Time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 2, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Hr." } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "RO Operation Time",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device40",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RO Supply Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "RO Supply Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device47",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
     "options": {
      "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'>1st Pass RO SYSTEM</span></h4>"
     }
    },
    {
     "title": "RO Pre-Filter Inlet Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "RO Pre-Filter Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device15",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RO Pre-Filter Outlet Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "RO Pre-Filter Outlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device16",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RO Pre-Filter Diff Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "RO Pre-Filter Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device17",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "1st Pass RO Feed Array 1 Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "1st Pass RO Feed Array 1 Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device18",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "1st Pass RO Feed Array 2 Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "1st Pass RO Feed Array 2 Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device19",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "1st Pass RO Concentrate Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "1st Pass RO Concentrate Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device20",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "1st Pass RO Diff Array 1 Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "1st Pass RO Diff Array 1 Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device21",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "1st Pass RO Diff Array 2 Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "1st Pass RO Diff Array 2 Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device22",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "1st Pass RO Diff System Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "1st Pass RO Diff System Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device23",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "1st Pass RO Product Flow",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "m3/hr" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "1st Pass RO Product Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device28",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "1st Pass RO Reject Flow",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "m3/hr" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "1st Pass RO Reject Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device29",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "1st Pass RO %Recovery",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "1st Pass RO %Recovery",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device30",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "1st Pass RO Feed Conductivity",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "uS/cm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "1st Pass RO Feed Conductivity",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device34",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "1st Pass RO Product Conductivity",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "uS/cm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "1st Pass RO Product Conductivity",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device35",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "1st Pass RO %Salt Rejection",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "1st Pass RO %Salt Rejection",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device36",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "1st Pass RO Feed ORP",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "mV" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "1st Pass RO Feed ORP",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device39",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
     "options": {
      "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'>2nd Pass RO SYSTEM</span></h4>"
     }
    },
    {
     "title": "2nd Pass RO HP Pump Inlet Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 2, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "2nd Pass RO HP Pump Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device24",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "2nd Pass RO Inlet Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "2nd Pass RO Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device25",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "2nd Pass RO Concentrate Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "2nd Pass RO Concentrate Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device26",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "2nd Pass RO Concentrate Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "2nd Pass RO Concentrate Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device26",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "2nd Pass RO Diff System Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "2nd Pass RO Diff System Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device27",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "2nd Pass RO Product Flow",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "m3/hr" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "2nd Pass RO Product Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device31",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "2nd Pass RO Reject Flow",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "m3/hr" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "2nd Pass RO Reject Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device32",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "2nd Pass RO %Recovery",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "2nd Pass RO %Recovery",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device33",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
     "options": {
      "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'>Degas System</span></h4>"
     }
    },
    {
     "title": "Degas Inlet Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Degas Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device41",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Degas Outlet Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Degas Outlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device42",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Degas Diff Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Degas Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device43",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Degas Inlet pH",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Degas Inlet pH",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device44",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Degas Vacuum",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "psi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Degas Vacuum",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device46",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Degas Outlet pH",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Degas Outlet pH",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device45",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OVERALL SYSTEM",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 20, "x": 2, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "RO Pre-Filter Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device15",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "RO Pre-Filter Outlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device16",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "RO Pre-Filter Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device17",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Feed Array 1 Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device18",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Feed Array 2 Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device19",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Concentrate Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device20",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Array 1 Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device21",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Array 2 Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device22",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO System Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device23",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO HP Pump Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device24",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device25",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO Concentrate Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device26",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO System Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device27",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Permeate Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device28",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Reject Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device29",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO %Recovery",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device30",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO Permeate Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device31",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO Reject Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device32",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO %Recovery",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device33",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Feed Conductivity",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device34",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Permeate Conductivity",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device35",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO %Salt Rejection",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device36",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO Permeate Conductivity",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device37",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO %Salt Rejection",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device38",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Feed ORP",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device39",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "RO Operation Time",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device40",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Degas Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device41",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Degas Outlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device42",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Degas Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device43",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Degas Inlet pH",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device44",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Degas Outlet pH",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device45",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Degas Vacuum",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device46",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "RO Supply Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device47",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Chlorinated Water Tank Level",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device48",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "RO Feed Tank Level",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device49",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "RO Water Tank Level",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device50",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Trend Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "OVERALL SYSTEM",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 20, "x": 2, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "UF Pre-Filter Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device01",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Pre-Filter Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device02",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Feed Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device03",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Product Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device04",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF System TMP",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device05",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Feed Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device06",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Product Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device07",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Operation Time",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device08",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Feed Total Volume",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device09",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Product Total Volume",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device10",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Backwash Counter",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device11",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF CEB#1 Counter",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device12",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF CEB#2 Counter",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device13",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "UF Feed Chlorine",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device14",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "RO Pre-Filter Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device15",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "RO Pre-Filter Outlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device16",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "RO Pre-Filter Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device17",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Feed Array 1 Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device18",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Feed Array 2 Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device19",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Concentrate Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device20",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Array 1 Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device21",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Array 2 Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device22",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO System Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device23",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO HP Pump Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device24",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device25",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO Concentrate Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device26",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO System Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device27",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Permeate Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device28",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Reject Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device29",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO %Recovery",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device30",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO Permeate Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device31",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO Reject Flow",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device32",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO %Recovery",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device33",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Feed Conductivity",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device34",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Permeate Conductivity",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device35",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO %Salt Rejection",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device36",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO Permeate Conductivity",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device37",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "2nd Pass RO %Salt Rejection",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device38",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "1st Pass RO Feed ORP",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device39",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "RO Operation Time",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device40",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Degas Inlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device41",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Degas Outlet Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device42",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Degas Diff Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device43",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Degas Inlet pH",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device44",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Degas Outlet pH",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device45",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Degas Vacuum",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device46",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "RO Supply Pressure",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device47",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Chlorinated Water Tank Level",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device48",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "RO Feed Tank Level",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device49",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "RO Water Tank Level",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1/device50",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Alarm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
     "options": {
      "content": "<h4 class=\"contact_txt_company\" style=\"text-align: center;\"><span style='font-family: \"Times New Roman\", Times, serif; font-size: 26px;'>ALARM</span></h4>"
     }
    },
    {
     "title": "Alarm",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "alias": "Alarm Comment",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Site4/machine1//Alarm1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}